# fly.toml app configuration file generated for jaya-prakash-currency-converter on 2024-01-14T19:36:01-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jaya-prakash-currency-converter"
primary_region = "gru"
kill_signal = "SIGTERM"

[build]

[deploy]

[env]
  FLY_LAUNCH_MODE = "clone"
  PHX_HOST = "jaya-prakash-currency-converter.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
