name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app to fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --vm-memory 256 --yes --now
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
